### ISSUE TITLE
namenode start fail

### ISSUE THREAD

**Issue by lyon-yue** [dahaian/hadoop-kubernetes#1]
I start the demo in minikube. When start the namenode , it failed
![image](https://user-images.githubusercontent.com/39483524/45344454-59431f00-b5d6-11e8-97d6-10acfe22c1aa.png)
Is there anything to do before the demo?

**Comment by Alanthur** [comment]
Can you provide "describe po"? I think it is not enough permissions to create file of the image.

**Comment by lyon-yue** [comment]
使用docker edge版本，选择kubernetes重试后没有上面的问题了。可能是没有权限创建目录之类的问题。我尝试了在namenode容器内执行 curl localhost:50070/dfshealth.html可以访问页面，但是在我的mac浏览器中改怎么访问呢？我是个k8s的新手~

**Comment by Alanthur** [comment]
你可以把安装kubernetes的服务器里面的服务器的端口映射出来到本地，然后访问本地的端口去访问那个地址。可以把相关的svc端口映射出来，如果需要的话也可以你自己添加对应的svc端口

**Comment by lyon-yue** [comment]
搞定了
![image](https://user-images.githubusercontent.com/39483524/45545168-1be7c700-b84c-11e8-8f59-7bd3ee317227.png)

![image](https://user-images.githubusercontent.com/39483524/45545212-3f127680-b84c-11e8-9074-4de4009ce182.png)

**Comment by lyon-yue** [comment]
谢大佬
